### ISSUE TITLE
Develop basic deployment process

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#246]
### Enabler

So that we can deploy to production, we want a basic deployment process

#### Acceptance Criteria

- [x] Deployments are timely 
- [x] Deployment is automated as much as possible (and where practicable) (e.g. via GH actions)
- [x] Deployment manual steps can be documented and done by anyone in the product team
- [ ] Deployments can not be run in parallel
- [x] Deployments do not delete existing user generated content

#### Additional context

Assumption that content doesn't need to be migrated between new and old resources (particularly S3 buckets) during deployment.

#### Tasks

- [x] Develop single click process to start deployment (e.g. manual GH action to run deployment script)
- [x] Intermediate manual step in deployment to confirm what is going to be updated (CDK confirmation?) to avoid replaces resources with user content (could be automated later)

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
@imincik we added this one in your absence. Can you please review the tasks we came up with and we can discuss estimate/tasks etc if needed.

**Comment by imincik** [comment]
Do we want to support any kind of rollback feature or we are "rollforward" only ?

**Comment by imincik** [comment]
Deployment proposal documented here - https://confluence.linz.govt.nz/display/LGDL/Production+Deployment

**Comment by billgeo** [comment]
Looks fine to me. Have a left a couple of minor comments on the confluence page.

**Comment by billgeo** [comment]
Could you update the estimate of this one too please @imincik? I'm guessing it's probably less than a 13 for designing and implementing this?

**Comment by imincik** [comment]
@billgeo , production deployment is now finished and tested.

Current implementation is not fully matching acceptance criteria "Deployments can not be run in parallel". It it technically possible to launch multiple deployments in parallel if you submit more release tags at the same time, but I think this should solved by just avoiding doing so (I'll add this as note in our deployment documentation)

**Comment by billgeo** [comment]
Sounds good.

**Comment by imincik** [comment]
I added example of release process https://confluence.linz.govt.nz/display/LGDL/Production+Deployment
