### ISSUE TITLE
Implement dynamic batch job array size

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#269]
### Enabler

So that batch jobs run as fast and cheap as possible, we want to run only the minimum number necessary to validate the checksums of each asset in a dataset.

#### Acceptance Criteria
- [ ] Creating a dataset version for a dataset with only a single asset should start only a single instance of the check_files_checksums job.
- [ ] (Optional: riskier, but this would be a natural place to do it) We should enable running up to [10,000](https://docs.aws.amazon.com/batch/latest/userguide/array_jobs.html) check_files_checksums jobs in parallel.

#### Additional context

AWS Support Case ID 8001236181

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
