### ISSUE TITLE
Run tests in parallel

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#280]
### Enabler

So that tests run as fast as possible, we want to run them in parallel

#### Acceptance Criteria
- [ ] Pytest runs at least two tests in parallel.

#### Additional context

The biggest risk is with our tests having side effects affecting other tests.

#### Tasks

- [ ] Investigate options like built-in (if it exists), https://pypi.org/project/pytest-parallel/, https://pypi.org/project/pytest-xdist/ and others
- [ ] Run two or more tests in parallel, ideally concurrently rather than locked to the GIL

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by Jimlinz** [comment]
Briefly looked at this last week. I've had some success with running
`poetry run coverage run --append --module pytest -n auto --dist=loadfile --junitxml=junit.xml "--randomly-seed=${GITHUB_RUN_ID}" --verbosity=2` locally. Test runtime were cut in half.

I ran into some problems with nix-shell (after adding xdist to poetry), and have not spent any more time investigating.

**Comment by billgeo** [comment]
@l0b0 we're wondeirng if you could have a go at estimating fixing nix-shell for this so we can add ti to next sprint, while you are away. see  #2072

**Comment by Jimlinz** [comment]
There might be a bit more work involved in this unfortunately. It is possible for the tests to get into a race condition when running in parallel (particularly when multiple tests need to read or write the same root catalog). I thought `--dist=loadfile` would solve this (i.e. running tests in parallel grouped by file), but that appears to not have been the case. Although it happens very rarely, tests can and do fail if the run order happens to trigger a race condition.

This is still worth doing though. The amount of tests are increasing and we should find a way to speed things up...

**Comment by l0b0** [comment]
> This is still worth doing though. The amount of tests are increasing and we should find a way to speed things up...

Agreed. A few related ideas:

- Is it possible to report test failures loudly? If so we could make sure that the parallel test job reports to us (for example via email) whenever it fails. Especially important if the non-parallel run succeeds.
- We could make the parallel test job a copy of the current job, and run it manually. That way we can phase out the current job when ready, and it takes care of avoiding spurious alerts when the non-parallel run also fails.
- Can we parallelise based on a seed, like we already do for the test sequence? That way it should be at least a bit easier to reproduce locally.
- Will parallel test runs work with the current random test sequence?
- Is it possible to parallelise tests within a file? This probably boils down to whether parallelising works with randomising.
- When a test fails, is it possible to somehow log which other tests were running at the same time?
- Don't run things in parallel until we're pretty sure there are no more intermittently failing tests, *and* we have a good understanding of detecting and reproducing such failures. We should probably also collect root causes, such as not (sufficiently) randomising things which have to be unique, such as dataset title.

**Comment by Jimlinz** [comment]
A quick summary (of what I think is the problem) while it is still fresh in my mind. This is a non comprehensive list, so please feel free to add to it. There is a test called `test_populate_catalog::should_create_new_root_catalog_if_doesnt_exist`. This test assumes that the root catalog is missing from the geostore bucket. At the end of the test, `delete_s3_key` is called to delete the root catalog; thus leaving everything in a clean slate. Meanwhile (if running parallel test is enabled), it is possible that `test_processing_stack::should_successfully_run_dataset_version_creation_process_and_again_with_partial_upload` is called. This is a long running test. One of the checks in this test is to verify that an entry for the newly added dataset is found in the root catalog. During this time, it is possible that the previous test (`test_populate_catalog`) completes and deletes the root catalog. This means the `root catalog` cannot be updated, causing the second test to fail. This particular problem applies to a myriad of tests that require interaction with the root catalog (there are a few of them).

I briefly looked at mocking an s3 bucket locally (using `moto` or similar), but it doesn't seem like it would work. This is because the tests that fail are (mostly what I considered to be) integration tests, where dataset are run through the step function and batch processing, before ending up on the s3 bucket. I don't think we can get lambda to upload the files locally instead of an actual s3 bucket (unless we completely re-work all the tests to run step function and lambda locally). This doesn't seem like a viable option.

I also briefly thought about having a sister cdk stack that provision a number of s3 buckets for each of the tests that require one. That way, each test will have their own s3 bucket to work with, untouched by some other processes. The problem with this solution is, of course, `iam roles` and `permission`. We probably don't want to create extra roles or permission to allow the existing lambda to upload objects to foreign buckets. This will muck up the environment and could be a pain to troubleshoot if we encounter any problems in the future. 


Below is a summary of the top 10 longest running tests
```
============================================================== slowest 10 durations ==============================================================
168.98s call     tests/test_processing_stack.py::should_successfully_run_dataset_version_creation_process_with_single_asset
167.11s call     tests/test_processing_stack.py::should_successfully_run_dataset_version_creation_process_and_again_with_partial_upload
148.48s call     tests/test_processing_stack.py::should_successfully_run_dataset_version_creation_process_with_single_asset
90.82s call     tests/test_processing_stack.py::should_not_copy_files_when_there_is_a_checksum_mismatch
87.11s call     tests/test_processing_stack.py::should_not_copy_files_when_there_is_a_checksum_mismatch
72.12s call     tests/test_processing_stack.py::should_successfully_run_dataset_version_creation_process_and_again_with_partial_upload
71.48s call     tests/test_processing_stack.py::should_successfully_run_dataset_version_creation_process_and_again_with_partial_upload
68.96s call     tests/test_import_dataset.py::should_batch_copy_files_to_storage
46.31s call     tests/test_import_dataset.py::should_batch_copy_files_to_storage
13.62s call     tests/test_populate_catalog.py::should_add_link_to_root_catalog_in_series
```


Ideally, we want to kick off the long running tests in parallel so we can speed things up (i.e. if the top two long running tests are triggered the same time, it would be done in 168.98s, as opposed to 168.98s + 167.11s, so on and so forth).

**Comment by l0b0** [comment]
@Jimlinz Good summary, and yes, the stateful S3 tests are probably some of the most problematic. One way to circumvent that would be for the Geostore deployment to *create* the top-level catalogue iff it doesn't exist. In that case it's never valid for the catalogue to be absent in a properly deployed system.

**Comment by Jimlinz** [comment]
Having a persistent root catalog between tests might be an idea (to prevent the root catalog from getting deleted prematurely between tests); however, this presents other challenges in that some of our tests looks for `STAC_REL_PARENT` and `STAC_REL_ROOT` within in the `root catalog`. When running pytest in parallel, it is possible that these attributes are edited out of order between runs. This also present another problem where testing for `STAC_REL_ROOT` might return a false positive (i.e. there may be a problem with adding an entry to the `root catalog`, but the test is passing because the attribute already exists and was created by another [prior] test)

**Comment by l0b0** [comment]
> This also present another problem where testing for `STAC_REL_ROOT` might return a false positive (i.e. there may be a problem with adding an entry to the `root catalog`, but the test is passing because the attribute already exists and was created by another [prior] test)

Our use of random values for basically everything (including dataset names) should avoid this, but it *is* a possibility. A wrongly passing test would be a very serious issue.
