### ISSUE TITLE
Make sure each asset has only one multihash

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#301]
### Enabler

An asset could appear more than once in a dataset. We do not consider this an error. This can however complicate the data flow to the checksum validator: a specific asset + multihash is only unique when we also know which position in which metadata file it has. This uniqueness is important in DynamoDB, where inserting an item with the same primary key as an existing item will replace the original item. To avoid having to include the metadata file URL and position in the item, we can validate that each asset URL only has a single multihash value across the whole dataset.

#### Acceptance Criteria

- [ ] Given a dataset with two different multihashes for the same asset file, when validating the metadata file, then validation should fail.
- [ ] Given a dataset with two identical multihashes for the same asset file, when validating the metadata file, then validation should succeed.

#### Tasks

- [ ] Change check_stac_metadata to fail validation when an asset has more than one unique multihash.

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
