### ISSUE TITLE
Use automatically generated AWS resource names - spike

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#325]
### Enabler

To avoid problems during AWS stack updates when resource needs to be replaced and to avoid resource names conflicts per account or globally, we want to stop hard coding AWS resource names and leave AWS to generate unique name by itself.

We should consider keep human friendly name hard coding those resource names which are directly referenced by user (for example user role or Lambda endpoints) 

#### Acceptance Criteria

- [ ] All AWS resource names except human user accessed ones (Lambda function endpoints, Data Lake User role) contain automatically generated unique resource names

#### Tasks

- [ ] Spike to research at patching pynamodb or using something else
- [ ] Discuss and agree as a team how to move forward

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
I put an estimate on this. Whoever is working on it, can they please estimate it before they start work.

**Comment by l0b0** [comment]
Blocked by https://github.com/pytest-dev/pytest/issues/8485, unless we can use some other approach.
