### ISSUE TITLE
Use "should_" test function prefix for test discovery

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#334]
### Enabler

So that test names are shorter but still descriptive, we want to change the Pytest configuration to use `should_` as the test function prefix.

#### Acceptance Criteria

- [ ] Test function names start with `should_`
- [ ] Pytest still runs all the same tests as before.

#### Additional context

We already use `test_should_` as the de facto prefix.

#### Tasks

- [ ] [Configure Pytest](https://docs.pytest.org/en/stable/example/pythoncollection.html#changing-naming-conventions)
- [ ] Rename test functions.

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
