### ISSUE TITLE
Include at least S3 key in "access denied"/"not found" error messages when importing

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#351]
### User Story

So that I can quickly recover from an S3 permission/metadata error, as a dataset maintainer, I want to receive error messages which mention the S3 key of the file in question.

#### Acceptance Criteria

- [ ] Given a metadata file which the GDL does not have read access, when attempting to validate the metadata file, then the error message should include the S3 key of the file
- [ ] Given an asset file which the GDL does not have read access, when attempting to validate the file checksum, then the error message should include the S3 key of the file
- [ ] Given a metadata file which does not exist, when attempting to validate the metadata file, then the error message should include the S3 key of the file
- [ ] Given an asset file which does not exist, when attempting to validate the file checksum, then the error message should include the S3 key of the file

#### Tasks

- [ ] Add validation to 'check files checksum' tasks
- [x] Add validation to 'check STAC metadata' tasks

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [x] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
I put an estimate on this. Whoever is working on it, can they please estimate it before they start work.
