### ISSUE TITLE
Get alerts about code scanning alerts

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#357]
### Enabler

So that the GDL continues to be secure, we want to know about [code scanning alerts](https://github.com/linz/geospatial-data-lake/security/code-scanning)

#### Acceptance Criteria
- [x] Given I'm logged in as a user with admin access to this repo, then I should be able to sign up to be alerted about any new code scanning alerts
- [x] Given I've signed up for code scanning alerts, when a new code scanning issue is detected by GitHub I should be alerted within 1 hour

#### Tasks

- [x] Document how to set up the alert

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
