### ISSUE TITLE
Change paths in STAC metadata to relative paths

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#359]
### Enabler

So that we follow best practice for STAC catalogues, we want to switch from absolute paths in STAC metadata to relative paths (with an absolute path for the root metadata file for the entire DL)

#### Additional context

STAC recommendations are here: https://github.com/radiantearth/stac-spec/blob/master/best-practices.md

Having relative paths for all links except the root of the catalog, should support the following later user stories:
- Search/browse the entire Data Lake by metadata (TODO: add #)
- Export a collection of data/metadata (dataset) independently (TODO: add #)

#### Acceptance Criteria

- [x] given metadata with relative paths when I import my data then store paths as relative as per STAC recommendations 
- [x] given metadata with absolute or mixed paths when import my data, then convert and store paths as relative as per STAC recommendations 

#### Tasks

- [x] Add a function to do path transformations (from absolute to relative) after a file is copied. Could be separate AWS Step function task or S3 batch operation lambda.
- [x] Report any errors to 'import status' and say whether it is complete or not (integrate with pipeline status endpoint).
- [x] Change metadata validation to check that paths are valid (absolute or relative)

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
I put an estimate on this. Whoever is working on it, can they please estimate it before they start work.

**Comment by billgeo** [comment]
After talking to Blayne. It would be good to be able to take any path type and convert it relative paths.

**Comment by billgeo** [comment]
Tested and working well. I think. I don't know how to test navigating the paths, but it has copied the asset correctly so that seems to prove it can be navigated. Thanks @l0b0
