### ISSUE TITLE
Backup and Restore detailed design

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#408]
### Enabler

So that Data Lake content is well protected against potential data loss or corruption, we want to design proper data backup and restore processes.

#### Acceptance Criteria

- [ ] User data and application data backup and restore processes detailed design is created and accepted by Data Lake team 

#### Tasks

- [ ] Agree on Backup and Restore/Rollback requirements
- [ ] Discuss Backup and Restore/Rollback options meeting requirements
- [ ] Create Detailed design
- [ ] Create follow-up stories

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by imincik** [comment]
@billgeo , this Story is not relevant anymore. Do we want to replace it with some more relevant detailed design story or just update current one ?

**Comment by billgeo** [comment]
I think we close this one and create new stories. We had a quick conversation with Terence and made some decisions which can be the work we did on this one.
