### ISSUE TITLE
Document and Test Backup and Restore of Application Database

### ISSUE THREAD

**Issue by imincik** [linz/geospatial-data-lake#451]
### User Story

So that content of Data Lake Application DB is safely stored and maintained, as a Data Lake Maintainer, I want to ensure that Data Lake application DB can be regularly backed up and in event of any corruption can be restored to latest non corrupted state.

#### Acceptance Criteria

- [x] Given Data Lake Application DB contains any data, when any Application DB corruption happen, then the table content can be restored to latest non corrupted state by following documentation
- [x] Given a DB corruption has happened, when a restore is completed, then the restore should not change the configuration of the resource (DynamoDB) and the AWS stack

#### Tasks

- [x] Document process
- [x] Test process

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by imincik** [comment]
Backup and Restore process is documented and tested - https://confluence.linz.govt.nz/display/LGDL/Application+Database+Backup+and+Restore

**Comment by billgeo** [comment]
Thanks @imincik 

I think deleting all PITRs will be okay if:

1) You add some info to the docs about restoring multiple PITRs to cover us restoring the wrong one.
2) There is more detail about how to test the restored table before the original is deleted? What are our options there? How confident will we be that the system is working fine? Is it just some kind of diff query? Or cab we run software tests on the restored table somehow? Can we use the restored table in production before delete the original table?

**Comment by billgeo** [comment]
I would say document how you did it with dynamodb-table-sync and we can test it and adjust it later if we need to (like the repo falls out of maintenance or whatever). 

And if there any other backup methods to analyse the table then that could be useful to document as well? If it's not too much effort that is.

**Comment by imincik** [comment]
Documentation updated and is ready to be tested - https://confluence.linz.govt.nz/display/LGDL/Application+Database+Backup+and+Restore

**Comment by billgeo** [comment]
This looks good from my point of view. Moving back to in-progress for @MitchellPaff to test it.

**Comment by imincik** [comment]
Documentation updated again with on-place restore as default option.
