### ISSUE TITLE
Metadata validation should continue after encountering multiple directories error

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#453]
### User Story

So that I can get as much error information as possible when importing, as a dataset maintainer, I want to know about all "multiple directories" errors instead of only the first one.

#### Acceptance Criteria

- [ ] Given a dataset with more than one metadata file in a different directory from the root metadata file, when importing the dataset, then all metadata files in other directories are reported as user errors.
- [ ] Given a dataset with more than one asset file in a different directory from the root metadata file, when importing the dataset, then all asset files in other directories are reported as user errors.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
