### ISSUE TITLE
In-depth Demo prep

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#473]
### Enabler

So that we can ensure the Data Lake is fit for purpose, we want to do an in-depth demo and Q&A session with the Topo team that we are targeting for the first release

#### Acceptance Criteria

- [ ] Give Topo a full understanding of how they can use the data lake and what the limitations currently are
- [ ] Get on the spot feedback
- [ ] discuss how to get more in depth feedback post demo

#### Tasks

- [x] Create demo presentation
- [x] Create demo script/links etc
- [x] Add Topo processor devs to AD group before demo

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Ticket 10601234 raised to get Topo users added to the AD group.

**Comment by billgeo** [comment]
Got all this together. Just need to update my demo scripts with some changes that will be deployed this week.
