### ISSUE TITLE
Remove dataset type argument when creating dataset or version

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#478]
### User Story

So that creation requests are as simple as possible, as a dataset maintainer, I want to not have to specify the dataset type in the request to create a dataset or version.

The dataset type should be part of the metadata. Having it as a separate piece of metadata makes it really difficult to integrate with whatever solution we end up with for indexing our metadata.

#### Acceptance Criteria

- [ ] Given an otherwise valid dataset creation request, when a `type` argument is not specified, then the request should succeed
- [ ] Given an otherwise valid dataset version creation request, when a `type` argument is not specified, then the request should succeed

#### Additional context

We will stop storing the dataset type in the database as part of this.

#### Tasks

- [ ] Remove the `DATASET_TYPES` constant and work from there until the rest of the code works
- [ ] After completing the above, search for any remaining occurrences of "IMAGE" or "RASTER" in the code base

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Support this. I guess one thing to check is if this was implemented to support some future functionality? And some reason it needs to be in the DL database rather than in the dataset metadata.

**Comment by l0b0** [comment]
YAGNI - we don't know of any functionality which needs this yet, and it's probably the wrong place to implement it in any case since we already have a metadata store.
