### ISSUE TITLE
Report all STAC schema validation errors

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#482]
### User Story

So that I can fix more than one error at a time, as a dataset maintainer, I want to know of all the dataset errors when importing instead of just the first one encountered by the validator.

#### Acceptance Criteria

- [ ] Given a dataset with more than one schema validation issues in the same file (such as two missing required properties), when attempting to import it, then all such errors should be reported by the import status endpoint

#### Tasks

- [ ] Use [jsonschema's `iter_errors`](https://python-jsonschema.readthedocs.io/en/stable/validate/#jsonschema.IValidator.iter_errors) to loop through all errors, saving each of them to the validation results table

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
This would be good, but can go into the middle of the backlog somewhere I think.
