### ISSUE TITLE
Do in-depth demo

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#487]
### User Story

So that I get an understanding of how the Data Lake works, as a Topo Developer, I want to understand how it works and it's limitations.

#### Acceptance Criteria

- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Tasks

- [x] run through prior to demo and cut off merges/ changes before demo
- [x] set up date
- [x] do the demo
- [x] document feedback

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Demo done, stories created and prioritised
