### ISSUE TITLE
Test LINZ Data Service S3 'data source'

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#496]
### User Story

So that I can publish my data on the LINZ Data Service, as a Data Maintainer, I want to connect the LINZ Data Service using the AWS S3 'data source' type.

#### Acceptance Criteria

- [x] Given an LDS supported dataset in the Data lake, when I try to set up a data source, then it successfully authenticates.
- [x] Given an LDS supported dataset in the Data lake, when I try to connect to the S3 data source, then I can input the directory/dataset I want to connect the LDS to.
- [x] Given an LDS an S3 data source has been set up, when I try to 'import' data, then it successful accesses and imports data into the LINZ Data Service.
- [x] Given an S3 data source has been set up, when new data is added (a new version) to the dataset, then the Data Maintainer can reconfigure the 'data source' with the new dataset version S3 URL, so they can 'scan' the LINZ Data Service to detect a change and flags that 'data source' for an 'update'. 

#### Additional context

Potential issues:

1. There are two options to set up a data source in the LDS, on a) the whole bucket, or b) per directory in a bucket (by a prefix). It would be ideal to support both, but please discuss with the Open Data team which is the preferred method once there are hundreds or thousands of datasets. Peformance may be an issue. Note: the existing Data Lake with 9.1 TB takes ~ 1:40 to scan, which means it is probably unfeasible to do option 'a'.
2. Currently a new S3 directory is created with every new version, so the LDS might not be able to detect updates? It needs a static S3 path I believe
3. UUIDs are not very user friendly. LDS Admin users will need to copy and paste these, or possibly browse them, depending on the outcome of issue 1 above. Need to test this with an admin user in the Open Data team.

Findings:

1. S3 versioning (as opposed to directory versioning) would make this more convenient, but LDS can still detect added and updated files the way it works now.
1. We need human readable dataset prefixes since LDS doesn't understand STAC.

#### Tasks

- [x] Get LDS account ID - talk to Open Data team or look at Data Lake 2 implementation: **276514628126**
- [x] Create a role with required permissions. Could we reuse this role for other things like generic read-only access for all LINZ staff? That would be awkward, because according to linz-data-lake/infra/data_stores/raster_stack.py the role is required to have a Koordinates-specific name, starting with "koordinates-s3-access".
- [x] Give LDS access to the role (configured in LDS Admin pages) - talk to Open Data team
- [x] Test dataset import - with Open Data team to make sure it works for them

- [ ] Add functionality to give the Data Maintainer or LDS Admin the S3 URL tot the latest version for a dataset (will create new User Story for this if needed)

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by iharrison** [comment]
The LDS IAM Role ARN is `arn:aws:iam::715898075157:role/koordinates-s3-access-raster-read-role`

**Comment by l0b0** [comment]
I believe the role in question is the one using that role, which looks to be 276514628126.

**Comment by billgeo** [comment]
Feedback from @iharrison :

1. Would be easier for updating if path to the current version was static
