### ISSUE TITLE
Split long lines in Markdown automatically

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#498]
### Enabler

So that we effortlessly get minimal Markdown diffs, we want to automate line splitting.

#### Acceptance Criteria

- [ ] Pre-commit hook which splits lines according to some maximum line length

#### Tasks

- [ ] Install line splitting formatter (maybe [prettier](https://prettier.io/)?)
- [ ] Set up pre-commit hook
- [ ] Format all tracked Markdown files

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
