### ISSUE TITLE
Continue pipeline in case of non-fatal STAC validation errors

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#508]
### User Story

So that I get as much information as possible out of the import process, as a dataset owner, I want to run the whole import process (except for copying files) even in case of errors.

#### Acceptance Criteria

- [ ] Given dataset with one valid root metadata file containing an asset with the wrong checksum and an invalid child metadata file, when importing the dataset, then both the invalid file and the wrong checksum should be reported.

#### Additional context

Basically boils down to not returning 1 from `check_stac_metadata` in case of non-fatal errors.

#### Tasks
- [ ] Stop raising exceptions after saving failed validation results
- [ ] Optional: Might be able to merge the `run` and `save` methods

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by l0b0** [comment]
Fixed in d3c5699ed827aeed9dd33f59389f16b613249414.
