### ISSUE TITLE
Forbid duplicate JSON object names

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#510]
### Enabler

So that avoid having to deal with more complex data structures than necessary, we want to forbid duplicate JSON object names

#### Acceptance Criteria

- [x] Given a metadata file which contains two assets with the same name, when importing the dataset, then the status report should include an error message about the duplicate name and no files should be imported

#### Tasks

- [x] Use `json.load(…, object_pairs_hook=…)` for this

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Tested and returned an error as expected. Thanks @l0b0
