### ISSUE TITLE
Try pystac

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#520]
### Enabler

So that we don't reinvent the wheel, we might want to use [pystac](https://github.com/stac-utils/pystac) to read, validate and manipulate STAC metadata.

#### Acceptance Criteria
- [x] pystac has been tried
- [ ] check with @palmerj on previous issues / learnings
- [ ] decision to continue using pystac, or not
- [ ] if continuing, fully implement it

#### Additional context

It might be easiest to introduce this in `import_metadata_file`, to see whether there are any snags.

#### Tasks

- [ ] Install pystac with the "validation" extra
- [ ] Replace STAC-handling code with pystac code where applicable

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by palmerj** [comment]
Happy to discuss. I'm on leave for 2 weeks from Monday. But will pop into office on 29yh of April so can quickly meet in person too.

**Comment by billgeo** [comment]
Initial results documented here by @MitchellPaff. https://confluence.linz.govt.nz/display/LGDL/Pystac+Investigation
