### ISSUE TITLE
Don't enforce inclusion of 'owning group' when creating a dataset on datasets-endpoint

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#522]
### User Story

So that I don't have to enter information that isn't yet required, as a Data Maintainer, I **don't** want to enter 'owning group' information when creating a dataset.

Note: this function may be reitroduced when needed, see story #515

#### Acceptance Criteria

- [x] Given an authorized data maintainer is requesting to create a dataset, when they don't specify an 'owning group', then there is no error and the dataset is created successfully
- [x] Given a data maintainer is reading the confluence user guide or Github USAGE.md, it is clear that they don't have to enter an owning group

#### Tasks

- [x] Remove owning group parameter from dataset creation endpoint
- [x] Cascade the above to filtering datasets and, removing DB fields, etc.
- [x] Remove references to owning group in documentation

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Do we need to consider how we might back capture this information later if we decide we need it in a later release of the Data Lake?

**Comment by l0b0** [comment]
> Do we need to consider how we might back capture this information later if we decide we need it in a later release of the Data Lake?

Not really. If we need it, we'll find a way to add it.
