### ISSUE TITLE
Use file:checksum rather than deprecated checksum:multihash

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#531]
### Enabler

So that we keep up with the standard, we want to [use the current `file:checksum` field rather than `checksum:multihash`](https://github.com/stac-extensions/file#checksums)

#### Acceptance Criteria

- [ ] Given a dataset which specifies asset file checksums as `file:checksum` properties, when importing the dataset the checksums are validated as per the values in those properties.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
