### ISSUE TITLE
Strictly validate metadata

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#550]
### User Story

So that the GDL can infer the semantics of all the metadata, as a dataset maintainer, I want to know of any unknown metadata fields.

#### Acceptance Criteria

- [ ] Given a metadata file with fields which are neither in the STAC standard nor in any of the extensions declared in `stac_extensions`, when I attempt to import the file, then the fields are reported as unknown, and I am given a hint about needing to declare any extensions I'm using.
- [ ] Given a metadata file with an extension field with an invalid value and the extension is declared in `stac_extensions`, when importing the file, then the value is reported as not fitting the value format in the extension schema.

#### Additional context

This issue should resolve https://github.com/linz/geospatial-data-lake/issues/549, and probably takes precedence.

#### Tasks

- [ ] Validate extension schemas
- [ ] Disallow unknown properties ([`additionalProperties`](https://json-schema.org/draft/2020-12/json-schema-core.html#additionalProperties))

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
@dwsilk @blacha what is your view on this? Would you rather us strictly check STAC extensions, or not?
