### ISSUE TITLE
Spike: How do users want to 'access, search and browse' the data lake?

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#553]
### Enabler

So that we can create user stories to support access, search and browse, we want to find out how Data Analyst users want to access, search and browse the metadata and the data/assets.

#### Acceptance Criteria

- [ ] The product team understands how some users want to access, search and browse the data lake data
- [ ] The product team can evaluate the user stories and create acceptance criteria and tasks to work on them

#### Additional context

Some initial feedback from some LINZ developers, is that Developers and Data Analysts will want to browse the S3 Bucket directly and not the metadata files or APIs.

Channels review will help with this and also feedback from Scion, Mapbox and GNZ who all have access to DL 2.

#### Tasks

- [ ] Decide list of users to target
- [ ] Workshop with users
- [ ] Analyse / collate the results
- [ ] Write user stories
- [ ] Share with stakeholders (particularly @palmerj @blacha )

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
