### ISSUE TITLE
Spike: what do we need to build to support Elevation Data Maintenance?

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#558]
### Enabler

So that we can create user stories to support maintenance of Elevation data, we want to find out how Elevation Data Maintainers want to import and maintain their data and metadata.

#### Acceptance Criteria

- [ ] The product team understands how Data Maintainers want to umport and maintain their data and metadata
- [ ] The product team can work on the user stories to fill the gaps in Data Lake functionality
 
#### Tasks

- [x] Decide list of users to target
- [x] Workshop current state with users
- [x] Analyse / collate the results of current state
- [x] Workshop future state with Topo architects and POs
- [x] Write user stories for future state

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Next steps are to workshop a future state with Topo team (make sure we get info about what is changing with the Topo Processor). Then write user stories.

**Comment by billgeo** [comment]
Current state and future state updated.
Existing user stories already cover the work needed. Mainly

https://github.com/linz/geospatial-data-lake/issues/528
https://github.com/linz/geospatial-data-lake/issues/496

**Comment by billgeo** [comment]
https://confluence.linz.govt.nz/display/LGDL/User+Flows
