### ISSUE TITLE
Spike: can we make the UUIDs more user friendly?

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#572]
### User Story

So that I can browse the Data Lake with the S3 API, as a Developer or Data Analyst, I want the directory names including the UUIDs to be as user friendly as possible.

This shouldn't replace other, richer ways to browse the data, e.g. via STAC files/API.

#### Acceptance Criteria

- [x] Given that the S3 paths will be prefixed with human readable information, when a UUID is presented to the user, we know which style of UUID is as useable as possible by the end user (doesn't get in the way of reading the human readable part)
- [x] Given the best UUID format is different from the current implementation, when we come to work on a user story to change it, then we have the information needed to make it 'ready'

#### Tasks

- [x] Research UUID formats - 2 
- [x] Decide which one is the least annoying to have as a suffix on names in the S3 path
- [x] Make any changes needed - 1

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by l0b0** [comment]
Done in https://github.com/linz/geospatial-data-lake/pull/635
