### ISSUE TITLE
Lock version of hadolint

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#578]
### Enabler

So that our pipeline doesn't get blocked by an update to the hadolint Docker image, we want to use a specific version of hadolint.

#### Acceptance Criteria

- [ ] The version of hadolint which runs in the pipeline is fixed per commit

#### Additional context

If there is a Python package wrapping hadolint we should probably use that (_there isn't_), since then we'd be able to use the existing package update mechanism. Otherwise we might have to just lock a version of the Docker image in the pre-commit configuration.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
