### ISSUE TITLE
Add AWS credentials for dependabot

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#595]
### Enabler

So that dependabot automatic PRs build successfully on the first run, we want to give dependabot the necessary credentials

#### Acceptance Criteria

- [ ] Automatic dependabot PRs successfully complete the "Configure AWS credentials" pipeline step on the first try

#### Additional context

The job output:

```
Run aws-actions/configure-aws-credentials@v1
Error: Credentials could not be loaded, please check your action inputs: Could not load credentials from any providers
```

Re-running the job makes this step pass, because secrets access depends on who's triggering the action and the event which triggers it.

#### Tasks

- [x] Add `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` to the [dependabot secrets](https://github.com/linz/geospatial-data-lake/settings/secrets/dependabot)

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by imincik** [comment]
Following credentials where added to Dependabot secrets:

* AWS_ACCESS_KEY_ID
* AWS_SECRET_ACCESS_KEY
* AWS_ASSUME_ROLE_CI

**Comment by l0b0** [comment]
This seems to be an issue still, possibly because of even stricter settings on GitHub's side. [Discussion](https://github.com/dependabot/dependabot-core/issues/3253)

**Comment by imincik** [comment]
Dependabot secrets where updated with new AWS keys

**Comment by imincik** [comment]
Dependabot is still failing, looks like having Dependabot > Secrets doesn't help at all. Strange, why they exist then ? Potential fix might me changing triggering event from `pull_request` to `pull_request_target` which is not secure.

**Comment by imincik** [comment]
It looks to me that Dependabot Secrets are usable used only in `dependabot.yml` file

**Comment by billgeo** [comment]
We will accept the manual workaround for now.
