### ISSUE TITLE
Browse datasets with S3 API

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#609]
### User Story

So that I can browse the Data Lake to find the data I want using my existing tools, as a Developer or Data Analyst, I want the option to browse the Data Lake 'datasets' using the S3 API (command line and/or common S3 browsers)

This shouldn't replace other, richer ways to browse the data, e.g. via STAC files/API.

#### Acceptance Criteria

- [x] Given a multiple datasets imported, when an authenticated readonly user starts browsing the datasets (first directory level in the bucket), then the user is presented with human readable directory names (includes dataset title?)
- [x] Given a naming convention has been set for the entire Data Lake, when a Data Maintainer creates a Dataset that doesn't meet the naming convention, then the dataset creation is aborted and a suitable message returned to the user.

#### Tasks

- [x] add a user provided prefix (normalised title) to dataset name
- [x] restrict what characters can be used for a dataset title (cross platform and human readable etc)

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Looks great. Thanks @l0b0
