### ISSUE TITLE
Browse data versions using S3 API

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#610]
### User Story

So that I can find the data I want using my existing tools, as a Developer or Data Analyst, I want to evaluate which version I need for dataset or a file using the S3 API (command line and/or common S3 browsers)

This shouldn't replace other, richer ways to browse the data, e.g. via STAC files/API.

#### Acceptance Criteria

- [x] Given S3 versioning is enabled, when an authenticated readonly user requests the versions for the file, then they can get a list of versions for the file with useful metadata
- [x] Given there multiple versions for a dataset stored as S3 directories, when an authenticated readonly user browses to a dataset they can get a list of versions with human readable names (including useful metadata such as a timestamp)

#### Tasks

- [x] Investigate using a UUID type that can be ordered by date
- [x] add a datetime prefix to version name

#### Definition of Ready
- [x] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Looks great. Thanks @l0b0
