### ISSUE TITLE
Spike: can we use S3 redirection to rename a dataset?

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#616]
### Enabler

So that we can rename datasets without breaking existing paths to datasets, we want to find out if we can redirect S3 prefixes in AWS

#### Acceptance Criteria

- [ ] Given a object with a prefix, when we want to rename that prefix, we know how to redirect the original prefi to the new prefix (is this right?)

#### Tasks

- [ ] do brief investigation of redirecting S3 prefixes when renaming 
- [ ] document the results somewhere so that we can implement when needed

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by l0b0** [comment]
## Findings

[S3 redirects](https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-page-redirect.html) only apply to *web links.* That is, if the S3 bucket is configured for website hosting (an optional feature), going to https://hostname-corresponding-to-s3-bucket/old-name can redirect to https://hostname-corresponding-to-s3-bucket/new-name. Asking users to use HTTP rather than raw S3 for accessing the files would probably destroy several of our use cases, such as doing bulk copy to another bucket.

**Comment by billgeo** [comment]
Okay thanks. Make sense.
