### ISSUE TITLE
Spike: can we use S3 versions rather than manual versions?

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#618]
### Enabler

So that we can use standard AWS functionality and make it simpler (and possibly cheaper at the same time), we want to investigate if we can use S3 versions to maintain dataset versions

#### Acceptance Criteria

- We have enough information to make a decision on whether to use the existing versioning design, if we need to alter or if we need to replace it with something else like S3 versioning.
- We understand how the versioning design we choose will support or not support the user stories
- We have made a decision on how versioning will work, whether it's using the existing design or making changes

#### Additional context

There seems to be two level of versioning that are required. Some users wil be interested in versions of datasets, some may be interested in versions of individual files.

1. A 'dataset version' that is  defined as all the file changes from a single import operation. 
2. A 'file version' that is defined as all the changes for a single file/object within a dataset.

The user stories this needs to be designed for are in rough order of priority are:

Need in next 6 months:
#626 - Minimise cost of versioning
#623 - Restore previous version of a dataset 
#622 - List dataset versions
Probably need next year or two:
#560 - Notify new dataset versions
#610 - Browse file versions using S3 API
#624 - Export previous version of a dataset
#625 - Get list of changes for a dataset version
??? - Notify new file/object versions

#### Tasks

- [x] define use cases / user stories that we want solve
- [x] do some design/research to meet use cases using S3 versions
- [x] indicate which use cases can be solved and which can't

#### Definition of Ready
- [ ] This story is __ready__ to work on, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done
- [ ] This story is __done__, according to the [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
> #626 - Minimise cost of versioning 

easier with S3 versioning

> #623 - Restore previous version of a dataset 

easier with current implementation but could be done with s3 versioning

> #622 - List dataset versions

easier with current implementation

> #560 - Notify new dataset versions

easier with current implementation

> #610 - Browse file versions using S3 API

easier with S3 version

> #624 - Export previous version of a dataset

easier current implementation

> #625 - Get list of changes for a dataset version

Not easy for either implementation

> ??? - Notify new file/object versions
