### ISSUE TITLE
Make sure we use the same Python version everywhere

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#678]
### Enabler

So that we don't run into differences between how code runs locally, in the pipeline, and in production, we want to make sure we use the same version of Python

#### Acceptance Criteria

- [ ] Developers get alerted when the Python version running in the `public.ecr.aws/lambda/python:3.8` Docker image (or newer, when we upgrade) is different from the one mentioned in `.python-version`
- [ ] Enforce equality between the Python versions in our GitHub Actions configuration and `.python-version`, either by dynamically including that file in the configuration or detecting when they diverge.

#### Tasks

- [ ] ...
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)
