### ISSUE TITLE
Use consistent API parameter/response format

### ISSUE THREAD

**Issue by l0b0** [linz/geospatial-data-lake#685]
### Enabler

So that users and developers can easily learn the API, we want to use consistent naming in input and output.

#### Acceptance Criteria

- [ ] Adopt a common, simple naming scheme for API inputs and outputs

#### Additional context

The AWS scheme seems appropriate:

- The first word is lowercase, for example, `foo`
- The second and subsequent words are title case, for example, `fooBarBaz`
- Abbreviations in names are forced to title case rather than the original case, for example, `fooUrl`, *not* `fooURL`.

#### Tasks

- [ ] Update documentation in confluence help pages and USAGE.md
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by imincik** [comment]
Agreed to use `snake_case` at least for now.
