### ISSUE TITLE
Make bucket names more user friendly

### ISSUE THREAD

**Issue by billgeo** [linz/geospatial-data-lake#686]
### User Story

So that I can read and understand the S3 path to the data, as a data analyst or developer, I want the bucket names to be human readable with no system generated random strings

#### Acceptance Criteria

- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]
- [ ] Given [a pre-condition], when [an event happens], then [an expected outcome occurs]

#### Tasks

- [ ] on prod, have static bucket names with no system generated strings for any buckets (or any other resources) that the user can access via AWS CLI etc.
- [ ] ...

#### Definition of Ready

- [ ] This story is **ready** to work on, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

#### Definition of Done

- [ ] This story is **done**, according to the
      [team's definition](https://confluence.linz.govt.nz/pages/viewpage.action?pageId=87930423)

**Comment by billgeo** [comment]
Already done
